export const BOOKS_LIST_REQUEST = 'BOOKS_LIST_REQUEST'
export const BOOKS_LIST_SUCCESS = 'BOOKS_LIST_SUCCESS'
export const BOOKS_LIST_ERROR = 'BOOKS_LIST_ERROR'

export const BOOK_UPDATE_REQUEST = 'BOOK_UPDATE_REQUEST'
export const BOOK_UPDATE_SUCCESS = 'BOOK_UPDATE_SUCCESS'
export const BOOK_UPDATE_ERROR = 'BOOK_UPDATE_ERROR'

export const BOOK_SEARCH_REQUEST = 'BOOK_SEARCH_REQUEST'
export const BOOK_SEARCH_SUCCESS = 'BOOK_SEARCH_SUCCESS'
export const BOOK_SEARCH_ERROR = 'BOOK_SEARCH_ERROR'